### ISSUE TITLE
@fortawesome/pro-solid-svg-icons NOT FOUND

### ISSUE THREAD

**Issue by tkoseoglu** [KY-Programming/mantic-ui#11]
Module not found: Error: Can't resolve '@fortawesome/pro-solid-svg-icons' in 'C:\Code\TOLGA-Git\XENATECH\CalPIDS\CalPIDS Administrative Website\node_modules\@mantic-ui\angular\fesm2022'

I am just now getting this error. Please advice

**Comment by ky-one** [comment]
Solved with v16.9.1
